### ISSUE TITLE
Markbot screenshot

### ISSUE THREAD

**Issue by lexyfh** [lexyfh/modularity-mindfulness#2]
In markbot I have 22% difference for the small screenshot one and I can't figure out what's going on. I see that there is space between the first two articles that are shifting the rest of the page down but I have no margins or padding that should be interfering.

@wendywarren
@KarenMendozaGarza

**Comment by KarenMendozaGarza** [comment]
Morning!  
Would you mind sharing a screenshot of the markbot difference? Maybe I can pick it out.

**Comment by KarenMendozaGarza** [comment]
From looking at your site, I'm wondering if it might be an issue with your footer. 

You currently have all the styling applied to the footer p: 
```
footer p {
  text-align: center;
  font-size: .75rem;
  padding-bottom: 1rem;
  border-top: .2rem solid #e2e2e2;
  padding-top: 1rem;
  margin-top: .5rem;
}
```
I would try removing all the styling from the p (which should actually change to a small tag), and putting it on the footer instead. So it would be something like this: 

```
footer {
  border-top: 0.2rem solid #e2e2e2;
  padding-top: 1rem;
  text-align: center;
}
```
Once you change the footer p to a small, you won't need the font size change and it should also get rid of any unnecessary margins.

**Comment by lexyfh** [comment]
<img width="860" alt="Screen Shot 2022-02-04 at 9 08 20 AM" src="https://user-images.githubusercontent.com/84150431/152542986-5ad798a2-a471-4580-a321-7c92d6f0101f.png">
 I don't think it did anything

**Comment by KarenMendozaGarza** [comment]
Oh, I see! 

Try removing the grid-template-rows from your section in the main css (not the media query)

**Comment by lexyfh** [comment]
<img width="482" alt="Screen Shot 2022-02-04 at 9 46 51 AM" src="https://user-images.githubusercontent.com/84150431/152548989-3c0acae2-fc2d-4b06-90a5-c16050c808c9.png">
So that helped a lot, I also changed the bottom margin for the section p but its at 15%, looks like i have an extra line of text than markbot?

@KarenMendozaGarza

**Comment by KarenMendozaGarza** [comment]
I dont think you should need a margin on the p. I noticed you don't have any spacing set up for your flex container in your article css. Could you try to justify the content, ad see if that does it?

**Comment by lexyfh** [comment]
It's still at 15%

@KarenMendozaGarza

**Comment by KarenMendozaGarza** [comment]
I think getting your footer to match a bit closer would put you under the 15%. Changing the copyright info to the appropriate `small` tag will get rid of any auto margins the browser gives to `p` tags, and then you could just add a `margin-top` to your footer to push the content away from the line a bit.

**Comment by KarenMendozaGarza** [comment]
Hi lexy, 
Please remember to close your issues when they have been resolved:)
