### ISSUE TITLE
Markbot validation

### ISSUE THREAD

**Issue by lexyfh** [lexyfh/modularity-mindfulness#3]
<img width="1792" alt="Screen Shot 2022-02-04 at 11 55 00 AM" src="https://user-images.githubusercontent.com/84150431/152569961-81c4705a-7e67-4c67-81a4-34d0df2ecc32.png">

Anything I do to try and fix these errors only creates more
@KarenMendozaGarza
@wendywarren

**Comment by lexyfh** [comment]
@wendywarren

**Comment by wendywarren** [comment]
Hi @lexyfh,

Looks like Markbot was guiding you to fix spacing for the code within the media query.

I adjusted it on my end which seemed to work. 

```
@media only screen and (min-width: 38em) {

  section {
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr;
  }

  header {
    flex-direction: row;
    justify-content: space-between;
  }
  
}
```

You were just missing some spaces and not putting the closing } on its own line.

Give it a shot and let me know how it goes.

Thanks,
Wendy

**Comment by lexyfh** [comment]
It worked! Didn't know I needed all the spacing, thank you! :)
@wendywarren
